//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuGroup
    {
        public int mnug_MenuGroupID { get; set; }
        public Nullable<int> mnug_CreatedBy { get; set; }
        public Nullable<System.DateTime> mnug_CreatedDate { get; set; }
        public Nullable<int> mnug_UpdatedBy { get; set; }
        public Nullable<System.DateTime> mnug_UpdatedDate { get; set; }
        public string mnug_Name { get; set; }
        public string mnug_Note { get; set; }
        public Nullable<int> mnug_Deleted { get; set; }
    }
}
