//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Admin_API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTableGroup
    {
        public int tblg_TableGroupID { get; set; }
        public Nullable<int> tblg_CreatedBy { get; set; }
        public Nullable<System.DateTime> tblg_CreatedDate { get; set; }
        public Nullable<int> tblg_UpdatedBy { get; set; }
        public Nullable<System.DateTime> tblg_UpdatedDate { get; set; }
        public string tblg_Name { get; set; }
        public string tblg_Note { get; set; }
        public Nullable<int> tblg_Deleted { get; set; }
    }
}
